<?php
namespace strong\components;

use api\consts\ErrorCode;
use Yii;
use yii\base\Component;
use yii\base\Exception;

/**
 * Class EasySms
 * @package strong\components
 */
class EasySms extends Component
{
    public $config;

    public $easySms;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->easySms = new \Overtrue\EasySms\EasySms($this->config);
    }

    public function __call($name, $params)
    {
        try{
            return call_user_func([$this->easySms, $name], $params);
        }catch (\Overtrue\EasySms\Exceptions\NoGatewayAvailableException $e){
            Yii::error($e->getLastException()->raw['errmsg'],'user');
            throw new Exception('短信服务', ErrorCode::THIRD_ERROR);
        }
    }
}